[2021-06-06 23:25:33,942] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: create_rox_tables.create_salesorderdetail_table 2021-06-06T23:25:11.492307+00:00 [queued]>
[2021-06-06 23:25:33,950] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: create_rox_tables.create_salesorderdetail_table 2021-06-06T23:25:11.492307+00:00 [queued]>
[2021-06-06 23:25:33,950] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-06 23:25:33,950] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-06-06 23:25:33,951] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-06 23:25:33,960] {taskinstance.py:1087} INFO - Executing <Task(PostgresOperator): create_salesorderdetail_table> on 2021-06-06T23:25:11.492307+00:00
[2021-06-06 23:25:33,966] {standard_task_runner.py:52} INFO - Started process 130 to run task
[2021-06-06 23:25:33,968] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'create_rox_tables', 'create_salesorderdetail_table', '2021-06-06T23:25:11.492307+00:00', '--job-id', '38', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/create_rox_tables.py', '--cfg-path', '/tmp/tmpzu4p02g8', '--error-file', '/tmp/tmplt9fildg']
[2021-06-06 23:25:33,969] {standard_task_runner.py:77} INFO - Job 38: Subtask create_salesorderdetail_table
[2021-06-06 23:25:33,995] {logging_mixin.py:104} INFO - Running <TaskInstance: create_rox_tables.create_salesorderdetail_table 2021-06-06T23:25:11.492307+00:00 [running]> on host 21bd802337aa
[2021-06-06 23:25:34,030] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_rox_tables
AIRFLOW_CTX_TASK_ID=create_salesorderdetail_table
AIRFLOW_CTX_EXECUTION_DATE=2021-06-06T23:25:11.492307+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-06-06T23:25:11.492307+00:00
[2021-06-06 23:25:34,030] {postgres.py:70} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS SalesOrderDetail
    (
        SalesOrderID INTEGER NOT NULL,
        SalesOrderDetailID INTEGER NOT NULL,
        CarrierTrackingNumber VARCHAR(20),
        OrderQty INTEGER,
        ProductID INTEGER,
        SpecialOfferID INTEGER,
        UnitPrice FLOAT,
        UnitPriceDiscount FLOAT,
        LineTotal FLOAT,
        rowguid VARCHAR(36),
        ModifiedDate TIMESTAMP,
        PRIMARY KEY (SalesOrderID, SalesOrderDetailID),
        FOREIGN KEY (SalesOrderID)
            REFERENCES SalesOrderHeader(SalesOrderID),
        FOREIGN KEY (SpecialOfferID, ProductID)
            REFERENCES SpecialOfferProduct(SpecialOfferID, ProductID),
        FOREIGN KEY (ProductID)
            REFERENCES Product(ProductID)
    )
[2021-06-06 23:25:34,036] {base.py:78} INFO - Using connection to: id: redshift. Host: doxcluster.craeubgpe2r5.us-east-1.redshift.amazonaws.com, Port: 5439, Schema: dox, Login: doxuser, Password: ***, extra: {}
[2021-06-06 23:25:35,668] {dbapi.py:204} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS SalesOrderDetail
    (
        SalesOrderID INTEGER NOT NULL,
        SalesOrderDetailID INTEGER NOT NULL,
        CarrierTrackingNumber VARCHAR(20),
        OrderQty INTEGER,
        ProductID INTEGER,
        SpecialOfferID INTEGER,
        UnitPrice FLOAT,
        UnitPriceDiscount FLOAT,
        LineTotal FLOAT,
        rowguid VARCHAR(36),
        ModifiedDate TIMESTAMP,
        PRIMARY KEY (SalesOrderID, SalesOrderDetailID),
        FOREIGN KEY (SalesOrderID)
            REFERENCES SalesOrderHeader(SalesOrderID),
        FOREIGN KEY (SpecialOfferID, ProductID)
            REFERENCES SpecialOfferProduct(SpecialOfferID, ProductID),
        FOREIGN KEY (ProductID)
            REFERENCES Product(ProductID)
    ), parameters: None
[2021-06-06 23:25:36,493] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=create_rox_tables, task_id=create_salesorderdetail_table, execution_date=20210606T232511, start_date=20210606T232533, end_date=20210606T232536
[2021-06-06 23:25:36,513] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-06-06 23:25:36,553] {local_task_job.py:151} INFO - Task exited with return code 0
