[2021-06-06 23:25:23,753] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: create_rox_tables.create_customer_table 2021-06-06T23:25:11.492307+00:00 [queued]>
[2021-06-06 23:25:23,761] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: create_rox_tables.create_customer_table 2021-06-06T23:25:11.492307+00:00 [queued]>
[2021-06-06 23:25:23,761] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-06 23:25:23,761] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-06-06 23:25:23,762] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-06 23:25:23,773] {taskinstance.py:1087} INFO - Executing <Task(PostgresOperator): create_customer_table> on 2021-06-06T23:25:11.492307+00:00
[2021-06-06 23:25:23,786] {standard_task_runner.py:52} INFO - Started process 107 to run task
[2021-06-06 23:25:23,790] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'create_rox_tables', 'create_customer_table', '2021-06-06T23:25:11.492307+00:00', '--job-id', '35', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/create_rox_tables.py', '--cfg-path', '/tmp/tmp3o16ryh0', '--error-file', '/tmp/tmpi01p5bug']
[2021-06-06 23:25:23,790] {standard_task_runner.py:77} INFO - Job 35: Subtask create_customer_table
[2021-06-06 23:25:23,820] {logging_mixin.py:104} INFO - Running <TaskInstance: create_rox_tables.create_customer_table 2021-06-06T23:25:11.492307+00:00 [running]> on host 21bd802337aa
[2021-06-06 23:25:23,854] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_rox_tables
AIRFLOW_CTX_TASK_ID=create_customer_table
AIRFLOW_CTX_EXECUTION_DATE=2021-06-06T23:25:11.492307+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-06-06T23:25:11.492307+00:00
[2021-06-06 23:25:23,855] {postgres.py:70} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS Customer
    (
        CustomerID INTEGER NOT NULL,
        PersonID INTEGER,
        StoreID INTEGER,
        TerritoryID INTEGER,
        AccountNumber VARCHAR(10),
        rowguid VARCHAR(36),
        ModifiedDate TIMESTAMP,
        PRIMARY KEY (CustomerID),
        FOREIGN KEY (PersonID) REFERENCES Person(BusinessEntityID)
    )
[2021-06-06 23:25:23,861] {base.py:78} INFO - Using connection to: id: redshift. Host: doxcluster.craeubgpe2r5.us-east-1.redshift.amazonaws.com, Port: 5439, Schema: dox, Login: doxuser, Password: ***, extra: {}
[2021-06-06 23:25:25,426] {dbapi.py:204} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS Customer
    (
        CustomerID INTEGER NOT NULL,
        PersonID INTEGER,
        StoreID INTEGER,
        TerritoryID INTEGER,
        AccountNumber VARCHAR(10),
        rowguid VARCHAR(36),
        ModifiedDate TIMESTAMP,
        PRIMARY KEY (CustomerID),
        FOREIGN KEY (PersonID) REFERENCES Person(BusinessEntityID)
    ), parameters: None
[2021-06-06 23:25:26,276] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=create_rox_tables, task_id=create_customer_table, execution_date=20210606T232511, start_date=20210606T232523, end_date=20210606T232526
[2021-06-06 23:25:26,350] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-06-06 23:25:26,374] {local_task_job.py:151} INFO - Task exited with return code 0
