[2021-06-06 23:25:17,460] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: create_rox_tables.create_person_table 2021-06-06T23:25:11.492307+00:00 [queued]>
[2021-06-06 23:25:17,469] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: create_rox_tables.create_person_table 2021-06-06T23:25:11.492307+00:00 [queued]>
[2021-06-06 23:25:17,469] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-06 23:25:17,469] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-06-06 23:25:17,470] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-06 23:25:17,480] {taskinstance.py:1087} INFO - Executing <Task(PostgresOperator): create_person_table> on 2021-06-06T23:25:11.492307+00:00
[2021-06-06 23:25:17,485] {standard_task_runner.py:52} INFO - Started process 96 to run task
[2021-06-06 23:25:17,487] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'create_rox_tables', 'create_person_table', '2021-06-06T23:25:11.492307+00:00', '--job-id', '33', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/create_rox_tables.py', '--cfg-path', '/tmp/tmpcnw2k95y', '--error-file', '/tmp/tmpb4a9hjh6']
[2021-06-06 23:25:17,488] {standard_task_runner.py:77} INFO - Job 33: Subtask create_person_table
[2021-06-06 23:25:17,513] {logging_mixin.py:104} INFO - Running <TaskInstance: create_rox_tables.create_person_table 2021-06-06T23:25:11.492307+00:00 [running]> on host 21bd802337aa
[2021-06-06 23:25:17,548] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_rox_tables
AIRFLOW_CTX_TASK_ID=create_person_table
AIRFLOW_CTX_EXECUTION_DATE=2021-06-06T23:25:11.492307+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-06-06T23:25:11.492307+00:00
[2021-06-06 23:25:17,548] {postgres.py:70} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS Person
    (
        BusinessEntityID INTEGER NOT NULL,
        PersonType VARCHAR(10),
        NameStyle INTEGER,
        Title VARCHAR(10),
        FirstName VARCHAR(50),
        MiddleName VARCHAR(50),
        LastName VARCHAR(50),
        Suffix VARCHAR(10),
        EmailPromotion INTEGER,
        AdditionalContactInfo VARCHAR(2000),
        Demographics VARCHAR(1000),
        rowguid VARCHAR(36),
        ModifiedDate TIMESTAMP,
        PRIMARY KEY(BusinessEntityID)
    )
[2021-06-06 23:25:17,554] {base.py:78} INFO - Using connection to: id: redshift. Host: doxcluster.craeubgpe2r5.us-east-1.redshift.amazonaws.com, Port: 5439, Schema: dox, Login: doxuser, Password: ***, extra: {}
[2021-06-06 23:25:19,077] {dbapi.py:204} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS Person
    (
        BusinessEntityID INTEGER NOT NULL,
        PersonType VARCHAR(10),
        NameStyle INTEGER,
        Title VARCHAR(10),
        FirstName VARCHAR(50),
        MiddleName VARCHAR(50),
        LastName VARCHAR(50),
        Suffix VARCHAR(10),
        EmailPromotion INTEGER,
        AdditionalContactInfo VARCHAR(2000),
        Demographics VARCHAR(1000),
        rowguid VARCHAR(36),
        ModifiedDate TIMESTAMP,
        PRIMARY KEY(BusinessEntityID)
    ), parameters: None
[2021-06-06 23:25:19,824] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=create_rox_tables, task_id=create_person_table, execution_date=20210606T232511, start_date=20210606T232517, end_date=20210606T232519
[2021-06-06 23:25:19,889] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-06-06 23:25:19,910] {local_task_job.py:151} INFO - Task exited with return code 0
